### ISSUE TITLE
Go 1.6 upgrade

### ISSUE THREAD

**Issue by anidotnet** [smarterclayton/openshift-go-cart#33]
Can you please upgrade the cartridge to support go 1.6?

**Comment by nhandl3** [comment]
I have created pull request #35. In the meanwhile you can use [my cartridge](https://github.com/whyka/openshift-go-cart) as an alternative.

**Comment by remisb** [comment]
I have a question. Is it possible to upgrade existing, already created gear with go cartridge to a latest version without recreating a new gear from scratch? 

For me it looks something irrational to have dependency on the go version to have specified in the openshift-go-cart/metadata/manifest.yml file. I see that as an critical missing customisation option. Will I have to update/recreate gear on every go lang update/release?
